### ISSUE TITLE
[HELP]: latest devcontainer breaks filesystem

### ISSUE THREAD

**Issue by mamedaliii** [freeCodeCamp/solana-curriculum#126]
### Project
Learn How to Set Up Solana by Building a Hello World Smart Contract
### Lesson Number
1
### Question
I am using VS code.

Step 1:

The first lesson is "Welcome to the Solana curriculum! For the duration of this project, you will be working in the learn-how-to-set-up-solana-by-building-a-hello-world-smart-contract/ directory."

The command that I write in the terminal:
cd learn-how-to-set-up-solana-by-building-a-hello-world-smart-contract

After clicking "Run Test" button "freeCodeCamp: Run Course" terminal shows me an Error:
 ERROR:  2023-03-21 16:21:16 Error: Could not find /workspace/solana-curriculum/.logs/.cwd.log
    at Object.getCWD (file:///workspace/solana-curriculum/.freeCodeCamp/tooling/test-utils.js:133:11)
    at async eval (eval at <anonymous> (file:///workspace/solana-curriculum/.freeCodeCamp/tooling/test.js:94:35), <anonymous>:1:31)
    at async file:///workspace/solana-curriculum/.freeCodeCamp/tooling/test.js:94:29
    at async Promise.allSettled (index 0)
    at async runTests (file:///workspace/solana-curriculum/.freeCodeCamp/tooling/test.js:122:22)
    at async FSWatcher.<anonymous> (file:///workspace/solana-curriculum/.freeCodeCamp/tooling/hot-reload.js:51:9)

As a result, I cannot run tests and continue the course. What is the issue and what can I do to fix it?

### Code and Screenshots
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/93679692/226731782-91b0e36e-20f4-410c-8b84-e5d607c97080.png">

**Comment by mamedaliii** [comment]
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/93679692/226744591-a620cd39-d0bc-4c58-8918-32f5fc785448.png">


There are the files. Strange... I do not remember that I changed or even somehow interact with them...

**Comment by ShaunSHamilton** [comment]
@mamedaliii The changes `settings.json`, `projects.json`, and `state.json` are expected. For everything else, I would revert the changes. Then, try again.

Let us know how that goes.

**Comment by mamedaliii** [comment]
@ShaunSHamilton I found the issue. The problem was solved by installing an older version of the Dev Container extension for VS code.

**Comment by ShaunSHamilton** [comment]
@mamedaliii Thank you for letting us know. I will close this for now, unless this comes up with others, or there is something that we need to change in the `.devcontainer` config
