### ISSUE TITLE
[Next] Release 2 Feedback

### ISSUE THREAD

**Issue by moT01** [freeCodeCamp/solana-curriculum#132]
I [previously went through the fourth project,](https://github.com/freeCodeCamp/solana-curriculum/pull/70#pullrequestreview-1289748798) so I skipped to the fifth one. Here's what I found:

**Container:**
I kept getting errors when building the container...
```
E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/main/t/tdb/libtdb1_1.4.3-0ubuntu0.20.04.1_amd64.deb  404  Not Found [IP: 91.189.91.38 80]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
[2023-03-30T02:57:17.124Z] The command '/bin/sh -c sudo apt-get install -y curl git bash-completion man-db firefox htop nano' returned a non-zero code: 100
```

I split that command in the Dockerfile to install nano and htop in two separate commands and it worked:
```
RUN sudo apt-get install -y nano
RUN sudo apt-get install -y htop
```

Not sure why that would happen - but it was pretty consistent. I got those errors twice, changed the dockerfile and it worked. Changed it back and got the errors again - changed it forward and it worked again. I did put nano before htop - maybe that had something to do with it. Not sure if you are seeing these.

**Repo:**
I'm sure you are aware, but the `_answer` folder is still there. Will want to remove that before release I presume.

**Project 5 - Metaplex NFT practice project:**
I really didn't run into much for problems - everything went pretty smooth 👍 just a bunch grammar suggestions...

Step 4: Maybe change the language to "copy the public key from the terminal" or something. I was looking for a CLI command to get me the public key, but it was in the terminal output from a previous step.

Step 16: Says to install a package - I presumed I should save it to the deps, so I ran `npm install --save @metaplex-foundation/js@0.18.1` - It added `@metaplex-foundation/js": "^0.18.1` to my package and the tests didn't pass cause of the `^`. Could maybe mention to use the `--save-exact` (I think) flag - or loosen the test to allow that caret.

Step 27 - Step 28: These, and some others, are quite long - it's a lot to try and take in. Overall the steps are worded nicely, there's a few that are just kind of long.

Step 30: Grammar error in the first sentence it seems

Step 35: Typo in last sentence "Stop you existing..." -> "Stop your existing..."

Step 36: AHHH - "For ease, this command has been added to the package.json" - I either can’t, or don’t know how to, copy from the simple browser - so I typed out that hash/ID. Can you copy from the simple browser? If this is a universal problem, could maybe mention that you can copy the key from the package.json.

Step 50: It wasn't clear right away that I need to run the file again - I figured it out quick, but it could maybe be mentioned.

Overall:
No real bugs. I got through all the steps pretty smoothly. Like I mentioned, some of the steps are a little long - I would like to see some of them broken up into shorter steps if possible, but I'm just mentioning it - no real need to do it.

It was a good project 👍 I felt very satisfied after finishing it.

**Project 6 - NFT integrated project:**
I didn't try to do much here yet. I just opened it up after finishing the practice project. I will try to complete it, or more of it, today or tomorrow.

- First paragraph has two sentences that sound the same.

**Comment by ShaunSHamilton** [comment]
> I kept getting errors when building the container...

I found the error:

```bash
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Package firefox is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'firefox' has no installation candidate
```

Anything installed after `firefox` breaks.

Do you remember why we include `firefox`?

**Comment by ShaunSHamilton** [comment]
> Step 4: Maybe change the language to "copy the public key from the terminal" or something. I was looking for a CLI command to get me the public key, but it was in the terminal output from a previous step.

You are supposed to `solana address -k <path_to_wallet>`. I think this would be obvious if you had more recently done the previous project/s

**Comment by ShaunSHamilton** [comment]
> Could maybe mention to use the --save-exact (I think) flag - or loosen the test to allow that caret.

```js
assert.equal(
  packageJson.dependencies['@metaplex-foundation/js'],
  '0.18.1',
  'Try running `npm install --save-exact @metaplex-foundation/js@0.18.1` in the terminal.'
);
```

Already do.

**Comment by ShaunSHamilton** [comment]
> Step 36: AHHH - "For ease, this command has been added to the package.json" - I either can’t, or don’t know how to, copy from the simple browser - so I typed out that hash/ID. Can you copy from the simple browser? If this is a universal problem, could maybe mention that you can copy the key from the package.json.

I can copy just fine. It could be Mac...
