### ISSUE TITLE
[BUG]:  Command `solana-test-validator --bpf-program...` not recognized as used

### ISSUE THREAD

**Issue by gikf** [freeCodeCamp/solana-curriculum#159]
### Issue/Experience
Learn the Metaplex SDK by Minting an NFT - Lesson 35 requires running in terminal command:
```
solana-test-validator --bpf-program metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s ./mlp_token.so --reset
```
Despite of running it, test might not recognize that. Due to how command from terminal is saved in temp for tests.

---
I had some troubles with passing this test. Seemingly everything was fine, but it still couldn't pass.
https://github.com/freeCodeCamp/solana-curriculum/blob/d4b889ef2c80f15b5ef012cc8ec658b83edceca6/curriculum/locales/english/learn-the-metaplex-sdk-by-minting-an-nft.md?plain=1#L2192-L2200

Meanwhile, copied from the `actual` field in the client console:
```
\u001b[01;32mroot\u001b[00m \u001b[01;34m/workspace/solana-curriculum/learn-the-metaplex-sdk-by-minting-an-nft\u001b[00m (main) $ \u001b[K🟢 DEBUG:  2023-05-02 13:49:48 Watcher: change - /workspace/solana-curriculum/.logs/.terminal-out.log
solana-test-validator --bpf-program metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s ./mlp_token.so --r\rreset
🟢 DEBUG:  2023-05-02 13:50:50 Watcher: change - /workspace/solana-curriculum/curriculum/locales/english/learn-the-metaplex-sdk-by-minting-an-nft.md
Ledger location: test-ledger
Log: test-ledger/validator.log
Initializing...
Waiting for fees to stabilize 1...
Waiting for fees to stabilize 2...
Connecting...
(...)
```

Relevant line:
```
solana-test-validator --bpf-program metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s ./mlp_token.so --r\rreset
```

As it can be seen ending differs from what is desired. How does `r\rr` gets there? It's from when long line entered to the terminal wraps itself.

After widening terminal a bit, so it doesn't wrap, test passed without issues.

---
Looks like terminal wrapping needs to be handled at some point. But, here in test, or at the step of reading from temp?

### Output of running `node tooling/camper-info.js` from the workspace root
```
🔵 INFO:   Project:  learn-the-metaplex-sdk-by-minting-an-nft
🔵 INFO:   Lesson Number:  1
🔵 INFO:   Curriculum Version:  0.2.0
🔵 INFO:   freeCodeCamp - Courses:  undefined
🔵 INFO:   Commit:  0ed5a55 chore(deps): update react monorepo

🔵 INFO:   OS Info: 
    Architecture: x64
    Platform: linux
    Release: 5.15.0-71-generic
    Type: Linux
```

**Comment by ShaunSHamilton** [comment]
Thanks for opening this.

If there is no easy way around the wrapping, the test could be changed to:

```javascript
const command = `curl http://127.0.0.1:8899 -X POST -H "Content-Type: application/json" -d '
  {
    "jsonrpc": "2.0",
    "id": 1,
    "method": "getProgramAccounts",
    "params": [
      "BPFLoader2111111111111111111111111111111111", {
        "encoding": "base64",
        "dataSlice": {
          "length": 0,
          "offset": 0
        }
      }
    ]
}'`;
const { stdout, stderr } = await __helpers.getCommandOutput(command);
try {
  const jsonOut = JSON.parse(stdout);
  assert.exists(
    jsonOut.result.find(
      r => r.pubkey === 'metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s'
    )
  );
} catch (e) {
  assert.fail(
    e,
    'Try running `solana-test-validator --bpf-program metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s ./mlp_token.so --reset`'
  );
}
```

**Comment by gikf** [comment]
I've unsuccessfully tried to change in `.bashrc` command saving to the log, to remove the `\r` in the text that's saved, but keep it in the terminal.

What worked was changing `getTemp` to return string with `\r` removed:
```
  return tempLogs.replace(/(.)\r\1/g, '$1');
```

Which appears to be much simpler. I'm unable to come up with an example when keeping `\r` might be needed for test case.

What do you think?

**Comment by ShaunSHamilton** [comment]
> What do you think?

Is the character before the `\r` always repeated after?

> I'm unable to come up with an example when keeping \r might be needed for test case.

I can imagine some cases where a `\n` might be important (see Tom's Bash/RDB course), but am not sure when a `\r` is useful over a `\n` - I do not understand why there is a `\r` and not a `\n`.

**Comment by gikf** [comment]
> Is the character before the `\r` always repeated after?

I thought so, but it's more interesting. When typing by hand character is not repeated, meanwhile it is repeated when text is pasted to the terminal. :eyes: 

However, when typing it, one can encounter different issue - any mistake will prevent test from passing. Even if it's corrected before command is submitted. The line in `.temp.log` will contain ie. `\b` for pressing backspace.

**Comment by ShaunSHamilton** [comment]
Ah, yes. I was not thinking about the prompt input like that.

In that case, I will document this behaviour as a warning when using `.temp.log`, and we should change this test to what I previously mentioned.
