### ISSUE TITLE
[failing at 13/20]: Dev Containers: Rebuild Container and Reopen in Container

### ISSUE THREAD

**Issue by ojasuno** [freeCodeCamp/solana-curriculum#276]
### Issue/Experience
unable to go beyond step 13/20 for this *Dev Containers: Rebuild Container and Reopen in Container*

### Output of running `node tooling/camper-info.js` from the workspace root

```
------
 > [dev_container_auto_added_stage_label 13/20] RUN sh -c "$(curl -sSfL https://release.solana.com/v1.16.11/install)":
1.835 downloading v1.16.11 installer
2.619 curl: (22) The requested URL returned error: 403 
2.625 solana-install-init: command failed: downloader https://release.solana.com/v1.16.11/solana-install-init-aarch64-unknown-linux-gnu /tmp/tmp.6oNimjYTkz/solana-install-init
------
```

**Comment by ShaunSHamilton** [comment]
Thank you for taking the time to open this.

What system are you running? (e.g. amd, arm, 32/64 bit, x86)

**Comment by serranoarevalo** [comment]
Seeing this as well on a M1 macOS

**Comment by ShaunSHamilton** [comment]
@serranoarevalo Please see: https://github.com/freeCodeCamp/solana-curriculum/issues/19

@ojasuno If you are also on M1, then this can be closed as a duplicate.
