### ISSUE TITLE
[BUG]: Tic-Tac-Toe-Part-1 

### ISSUE THREAD

**Issue by kamalbuilds** [freeCodeCamp/solana-curriculum#291]
### Issue/Experience

Simple Test cases are also not passing like the directory and some test cases like solana keygen are missing.

![image](https://github.com/freeCodeCamp/solana-curriculum/assets/95926324/9d7ac553-3408-46f0-a0e4-822b21ad5a37)

### Output of running `node tooling/camper-info.js` from the workspace root
![image](https://github.com/freeCodeCamp/solana-curriculum/assets/95926324/e6f7b6e3-3692-4377-ad3b-1afd17d5862f)

**Comment by ShaunSHamilton** [comment]
Thank you for taking the time to open this.

You have a lot of Git changes for the first lesson. Do you have unexpected changes in there? (about 6 are expected).

See: https://github.com/freeCodeCamp/solana-curriculum/issues/20

**Comment by ShaunSHamilton** [comment]
Closing as stale
