### ISSUE TITLE
[HELP]: "cargo build-sbf --sbf-out-dir=../../dist/program" returns "error: not a file: '/workspace/.local/share/solana/install/releases/1.14.7/solana-release/bin/sdk/bpf/dependencies/sbf-tools/rust/bin/rustc'"

### ISSUE THREAD

**Issue by AkiraMatthew** [freeCodeCamp/solana-curriculum#332]
### Project
Solana - Learn How to Set Up Solana by Building a Hello World Smart Contract 
### Lesson Number
29
### Question
I'm trying to run the cargo build-sbf but it keeps triggering that there is no such file
```cargo build-sbf --sbf-out-dir=../../dist/program```
```error: not a file: '/workspace/.local/share/solana/install/releases/1.14.7/solana-release/bin/sdk/bpf/dependencies/sbf-tools/rust/bin/rustc'```

I have no idea what to do, I've even searched the folder to create it, but no success either.
### Code and Screenshots
![image](https://github.com/freeCodeCamp/solana-curriculum/assets/87336992/4a3b8ee4-c7f3-4d95-a22b-c0a9d856eff6)

**Comment by ShaunSHamilton** [comment]
Hello there,

It seems like something has gone wrong with the installation of `solana`. Try running:

```bash
sh -c "$(curl -sSfL https://release.solana.com/stable/install)"
```

Then, use the `cargo build-sbf` command again.

**Comment by AkiraMatthew** [comment]
managed to solve it by updating my solana CLI to the 1.18.1 BETA release
```solana-install init 1.18.1```
