### ISSUE TITLE
[HELP]:  FreeCodeCamp Site blank then gives Error 4XX - 5XX

### ISSUE THREAD

**Issue by Yunbran** [freeCodeCamp/solana-curriculum#337]
### Project
Solana-Curriculum

### Lesson Number
Unable to start projects at all.

### Question

I can't seem to get the projects to show up on my freecodecamp site. The site loads without any projects, then it gives a 4xx-5xx after a few minutes. Any ideas how I could fix this?

### Code and Screenshots

![{D3B9F71E-EF61-4488-8D2D-50763FBCD3FD}](https://github.com/freeCodeCamp/solana-curriculum/assets/6510471/7048a3ea-1724-4b26-8940-7923a66c06c2)

![{45AAD29A-6B15-4B06-B253-0AB00A6A4DB5}](https://github.com/freeCodeCamp/solana-curriculum/assets/6510471/57b45f0b-71e1-408f-aaf6-19010935eded)

![{F9EBFEBE-9E69-4556-B787-C0F4E01920F4}](https://github.com/freeCodeCamp/solana-curriculum/assets/6510471/98b412c6-dcdc-46f8-8435-e70dbee51397)

**Comment by Yunbran** [comment]
Thank you Shaun, I have been able to get it started and running with gitpod rather than my local environment.

I'm excited to begin!

**Comment by ShaunSHamilton** [comment]
Excellent. I will close this for now, but if you manage to get it running locally, feel free to reply here with your solution to doing so.
