### ISSUE TITLE
[BUG]: ERROR: failed to solve: process "/bin/sh -c sh -c \"$(curl -sSfL https://release.solana.com/v1.16.11/install)\"" did not complete successfully: exit code: 1

### ISSUE THREAD

**Issue by voxelfox** [freeCodeCamp/solana-curriculum#339]
### Issue/Experience
Hi. I have tried to setup the Docker project using the standard workflow and I get the following:

### Output of running `node tooling/camper-info.js` from the workspace root
ERROR: failed to solve: process "/bin/sh -c sh -c \"$(curl -sSfL https://release.solana.com/v1.16.11/install)\"" did not complete successfully: exit code: 1

**Comment by voxelfox** [comment]
I seem to have resolved this issue by manually installing the Solana version:

curl -sSfL https://release.solana.com/v1.16.11/install -o solana_install.sh
chmod +x solana_install.sh
./solana_install.sh

**Comment by ShaunSHamilton** [comment]
Hello there,

Are you working on M1/2 architecture?

**Comment by voxelfox** [comment]
Hi @ShaunSHamilton that was M2. I ended up working on the tutorial on a Linux machine. 

Also, to note, I needed to manually install the solana cli with 1.18.12 and manually override the configuration files to use the profile created by solana-test-validator.
