### ISSUE TITLE
[BUG]: TypeError: Cannot read properties of undefined (reading 'match')

### ISSUE THREAD

**Issue by realtebo** [freeCodeCamp/solana-curriculum#47]
### Issue/Experience

I just discovered this course. So i followed step to build docker and to run course

The problem is that, from 'homepage' , when click on first link I got this

![image](https://user-images.githubusercontent.com/1268699/201339730-677a7485-9d02-4f34-8290-6fb90ac71d8f.png)

In the console I can see  this

```
root@49b33d235a9f:/workspace/solana-curriculum# cd . && NODE_ENV=production node ./.freeCodeCamp/tooling/server.js
🔵 INFO:  2022-11-11 07:20:01 Listening on port 8080
🔵 INFO:  2022-11-11 07:20:03 Watching for file changes on /workspace/solana-curriculum
file:///workspace/solana-curriculum/.freeCodeCamp/tooling/parser.js:200
  const mat = lesson.match(
                     ^

TypeError: Cannot read properties of undefined (reading 'match')
    at parseMarker (file:///workspace/solana-curriculum/.freeCodeCamp/tooling/parser.js:200:22)
    at getLessonDescription (file:///workspace/solana-curriculum/.freeCodeCamp/tooling/parser.js:62:23)
    at runLesson (file:///workspace/solana-curriculum/.freeCodeCamp/tooling/lesson.js:35:23)

Node.js v18.12.1
```

I already tried to shutdown the course and the restart.

This time, the home immediately changed into the server error page. 
The first time, It 'waited' for one my click, I think.

### Output of running `node tooling/camper-info.js` from the workspace root

🔵 INFO:   Project:  learn-how-to-set-up-solana-by-building-a-hello-world-smart-contract
🔵 INFO:   Lesson Number:  1
🔵 INFO:   Curriculum Version:  0.1.1
🔵 INFO:   freeCodeCamp - Courses:  freeCodeCamp.freecodecamp-courses@1.6.0
🔵 INFO:   Commit:  5cb8211 fix(deps): update rust crate solana-program to 1.14.7

🔵 INFO:   OS Info: 
    Architecture: x64
    Platform: linux
    Release: 5.15.49-linuxkit
    Type: Linux

**Comment by realtebo** [comment]
Same problem on home pc and on work pc, 2 different pc, always windows 11, always docker in Hyper-V mode.

I am rebuilding and retrying. Then I'll post the esit of the command

**Comment by realtebo** [comment]
Nothing changed (I also noticed your team pushed 2 commits, I was hoping but ... nothing changed)
```

root@d41076afcf7e:/workspace/solana-curriculum# cd . && NODE_ENV=production node ./.freeCodeCamp/tooling/server.js
🔵 INFO:  2022-11-11 12:45:57 Listening on port 8080
🔵 INFO:  2022-11-11 12:46:01 Watching for file changes on /workspace/solana-curriculum
file:///workspace/solana-curriculum/.freeCodeCamp/tooling/parser.js:200
  const mat = lesson.match(
                     ^

TypeError: Cannot read properties of undefined (reading 'match')
    at parseMarker (file:///workspace/solana-curriculum/.freeCodeCamp/tooling/parser.js:200:22)
    at getLessonDescription (file:///workspace/solana-curriculum/.freeCodeCamp/tooling/parser.js:62:23)
    at runLesson (file:///workspace/solana-curriculum/.freeCodeCamp/tooling/lesson.js:35:23)
    at async FSWatcher.<anonymous> (file:///workspace/solana-curriculum/.freeCodeCamp/tooling/hot-reload.js:47:7)

Node.js v18.12.1
```

Note: the output is the same when executing `develop course`

```
root@d41076afcf7e:/workspace/solana-curriculum# NODE_ENV=development node ./.freeCodeCamp/tooling/server.js
🔵 INFO:  2022-11-11 12:48:34 Listening on port 8080
🔵 INFO:  2022-11-11 12:48:36 Watching for file changes on /workspace/solana-curriculum
file:///workspace/solana-curriculum/.freeCodeCamp/tooling/parser.js:200
  const mat = lesson.match(
                     ^

TypeError: Cannot read properties of undefined (reading 'match')
    at parseMarker (file:///workspace/solana-curriculum/.freeCodeCamp/tooling/parser.js:200:22)
    at getLessonDescription (file:///workspace/solana-curriculum/.freeCodeCamp/tooling/parser.js:62:23)
    at runLesson (file:///workspace/solana-curriculum/.freeCodeCamp/tooling/lesson.js:35:23)

Node.js v18.12.1
root@d41076afcf7e:/workspace/solana-curriculum# 
```

**Comment by realtebo** [comment]
If needed:

**Comment by realtebo** [comment]
I add that after updating repo ad rebuilding the freecodecamp extension is no more installed.

something is broken

**Comment by ShaunSHamilton** [comment]
Thank you for all of the information. However, I am still unable to reproduce any issue.

The most likely cause for that message is a failure to copy the workspace contents during the docker build. That is, Docker did not successfully copy the necessary files from your local fs to the container.

You might have success running this course in Gitpod:


https://user-images.githubusercontent.com/51722130/201417516-cc902319-fa48-453d-89dc-2e730ee426ae.mp4

**Comment by ShaunSHamilton** [comment]
I am closing this as stale. I have been unable to reproduce this issue, and there does not seem to be many more coming into this problem.
