### ISSUE TITLE
feat: next

### ISSUE THREAD

**Issue by moT01** [freeCodeCamp/solana-curriculum#49]
Next ToDo:
Hide the project files in vscode settings again (https://github.com/freeCodeCamp/solana-curriculum/pull/50)
add feedback suggestions for second practice project (https://github.com/freeCodeCamp/solana-curriculum/pull/50)
finish integrated project(https://github.com/freeCodeCamp/solana-curriculum/pull/46)
enable reset on the practice project(s)?
remove any solutions

Announcement:
update news article
update web3-site
email all that signed up for updates

**Comment by ShaunSHamilton** [comment]
@moT01 Where are we on this?
