### ISSUE TITLE
[BUG]: Learn How to Interact with On-Chain Programs - `establishConnection` - async or not

### ISSUE THREAD

**Issue by gikf** [freeCodeCamp/solana-curriculum#72]
### Issue/Experience
There's inconsistency of whether `establishConnection` function should be asynchronous or not. While defined in the step 9, the problem can reveal itself as far as step 57.

Step 9 - Mentions exporting `async` function from `hello-world.js`.
Step 10 (and further) - Seed of the `hello-world.js` has synchronous function.
Step 11 - Last test uses `await` when calling `establishConnection`.
Step 12 - Mentions adding `const connection = establishConnection()` to the `main.js` file.
Step 13 (and further) - Seed of the `main.js` file, has `const connection = establishConnection()`.
Step 57 - Running `node src/client/main.js` results in error. I'm right now not entirely sure, but I recall this didn't stop all step tests from passing.

```
file:///workspace/solana-curriculum/learn-how-to-interact-with-on-chain-programs/src/client/hello-world.js:70
    const account = await connection.getAccountInfo(programId)
                                     ^

TypeError: connection.getAccountInfo is not a function
    at checkProgram (file:///workspace/solana-curriculum/learn-how-to-interact-with-on-chain-programs/src/client/hello-world.js:70:38)
    at main (file:///workspace/solana-curriculum/learn-how-to-interact-with-on-chain-programs/src/client/main.js:9:11)
    at async file:///workspace/solana-curriculum/learn-how-to-interact-with-on-chain-programs/src/client/main.js:13:1
```

### Output of running `node tooling/camper-info.js` from the workspace root
🔵 INFO:   Project:  learn-how-to-interact-with-on-chain-programs
🔵 INFO:   Lesson Number:  1
🔵 INFO:   Curriculum Version:  0.1.2
🔵 INFO:   freeCodeCamp - Courses:  freeCodeCamp.freecodecamp-courses@1.7.1
🔵 INFO:   Commit:  5526f1a chore(deps): update dependency @types/node to v18.11.13

🔵 INFO:   OS Info: 
    Architecture: x64
    Platform: linux
    Release: 5.15.0-56-generic
    Type: Linux

**Comment by ShaunSHamilton** [comment]
Thank you for opening this, and providing detailed steps.

`establishConnection` should **NOT** be `async`. So, I guess the error on step 57 is from you declaring it as `async`, and `connection` being a `Promise<Connection>` which does not have `.getAccountInfo`?

**Comment by gikf** [comment]
> `establishConnection` should **NOT** be `async`. So, I guess the error on step 57 is from you declaring it as `async`, and `connection` being a `Promise<Connection>` which does not have `.getAccountInfo`?

I had similar assumption regarding problem on the step 57.
