### ISSUE TITLE
[BUG]: Course runs on Windows but cannot click past the first screen

### ISSUE THREAD

**Issue by CamelJR** [freeCodeCamp/solana-curriculum#83]
### Issue/Experience
This issue occurs on Windows 10 while running the course in the VS Code simple browser window and google chrome browser.

The course screen appears, but clicking throws the message "focus lock" and doesn't do anything. I'm unable to get past the initial screen.

**Comment by ShaunSHamilton** [comment]
Hello there,

Please fill out the `Output of running node tooling/camper-info.js from the workspace root` section, when opening issues.

> I'm unable to get past the initial screen.

Are you saying the buttons do not do anything? Or, does the page go blank when interacting with it?

**Comment by CamelJR** [comment]
The former, exactly. The buttons do not do anything. I can sit on the initial screen and click 100 times.

/usr/bin/node ./tooling/camper-info.js
🔵 INFO:   Project:  learn-how-to-set-up-solana-by-building-a-hello-world-smart-contract
🔵 INFO:   Lesson Number:  1
🔵 INFO:   Curriculum Version:  0.1.3
🔵 INFO:   freeCodeCamp - Courses:  freeCodeCamp.freecodecamp-courses@1.7.1
🔵 INFO:   Commit:  46bb119 fix(deps): update dependency @solana/web3.js to v1.72.0
🔵 INFO:   OS Info: 
    Architecture: x64
    Platform: linux
    Release: 5.10.16.3-microsoft-standard-WSL2
    Type: Linux

**Comment by ShaunSHamilton** [comment]
Closing this issue as stale. We have recently updated the packages used. Hopefully, this has made the UI and server more stable.
