### ISSUE TITLE
[BUG]: Unable to click through on courses

### ISSUE THREAD

**Issue by BenWueb** [freeCodeCamp/solana-curriculum#96]
### Issue/Experience
I'm able to complete the install, everything appears to be working, however when I click on a course from my localhost nothing happens.
### Output of running `node tooling/camper-info.js` from the workspace root
: No such file or directory
BashRC Sourced
root@e155928fae0d:/workspace/solana-curriculum# node tooling/camper-info.js
🔵 INFO:   Project:  learn-how-to-set-up-solana-by-building-a-hello-world-smart-contract
🔵 INFO:   Lesson Number:  1
🔵 INFO:   Curriculum Version:  0.1.3
🔵 INFO:   freeCodeCamp - Courses:  freeCodeCamp.freecodecamp-courses@1.7.1
🔵 INFO:   Commit:  6d85871 fix(deps): update dependency @babel/parser to v7.20.13

🔵 INFO:   OS Info: 
    Architecture: x64
    Platform: linux
    Release: 5.10.16.3-microsoft-standard-WSL2
    Type: Linux

**Comment by ShaunSHamilton** [comment]
Thank you for taking the time to open this.

I am unable to reproduce any issues with the course. Are you able to see any additional logs in the terminal or the developer console?

**Comment by Sh1n** [comment]
Same issue here.

🔵 INFO:   Project:  learn-how-to-set-up-solana-by-building-a-hello-world-smart-contract
🔵 INFO:   Lesson Number:  1
🔵 INFO:   Curriculum Version:  0.1.3
🔵 INFO:   freeCodeCamp - Courses:  freeCodeCamp.freecodecamp-courses@1.7.1
🔵 INFO:   Commit:  6d85871 fix(deps): update dependency @babel/parser to v7.20.13

🔵 INFO:   OS Info: 
    Architecture: x64
    Platform: linux
    Release: 4.19.128-microsoft-standard
    Type: Linux

**Comment by ShaunSHamilton** [comment]
Closing this as stale. We have recently updated the packages used in this course. Hopefully this has made the UI and server more stable.
